[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway:start"
workingDirectory = "server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = { default = "5000" }
