[build]
builder = "nixpacks"
watchPatterns = ["**/*.js", "**/*.json"]
buildContext = "server"
buildCommand = "npm install && npx prisma generate && npx prisma db push"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "5000" }
